version: '3.1'

services:
  db:
    image: ankane/pgvector
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  app:
    build: .  # Add your Node.js application Dockerfile or use an image
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      POSTGRES_HOST: db         # Set the PostgreSQL host as the service name
      POSTGRES_PORT: 5432       # Default PostgreSQL port
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
